### ISSUE TITLE
Error compilando

### ISSUE THREAD

**Issue by ghost** [hugobullont/RevloClient#1]
Buenas,

Ayer encontré este proyecto y traté de compilarlo, sin embargo tuve error al no poseer el la firma hugobullont.pfx. Es probable que estoy preguntando algo muy básico, pero hay manera de omitir ese requerimento o tal vez me puedas ayudar con un poco más de información.

Por otro lado, no hubiera sido bueno hacer un "release" o el proyecto continua como WIP?

Saludos,

**Comment by hugobullont** [comment]
Hola, perdón por responder tan tarde a tu mensaje. RevloClient quedó en fase de testo antes de tener un release final. Desgraciadamente soy el único que estuvo trabajando en el y el tiempo lo tengo muy corto. Por otro lado, fácil este fin de semana me hago un tiempo para subir una nueva versión sin la firma.
